# AI/ML Topic Configuration Example
# Comprehensive configuration for monitoring Artificial Intelligence and Machine Learning

topic_metadata:
  name: "Artificial Intelligence & Machine Learning"
  slug: "ai-ml"
  description: "AI/ML developments, research, companies, tools, and industry trends"
  priority_level: "high"
  monitoring_frequency: "realtime"
  status: "active"
  created_date: "2025-07-27"
  last_updated: "2025-07-27"
  related_topics: ["claude", "openai", "llms", "computer-vision", "nlp"]
  keywords_primary: ["artificial intelligence", "machine learning", "AI", "ML", "deep learning", "neural networks", "LLM", "large language model", "transformer", "GPT", "Claude", "ChatGPT"]
  keywords_secondary: ["automation", "neural", "algorithm", "model training", "inference", "AGI", "artificial general intelligence", "computer vision", "NLP", "natural language processing", "reinforcement learning"]
  keywords_exclusion: ["artificial limb", "machine shop", "learning disability", "AI stock ticker"]

# Source Discovery and Mapping Configuration
source_mapping:
  tier_1_official:
    description: "Official AI company and research organization sources"
    discovery_patterns:
      - "Major AI company official blogs and announcements"
      - "Research institution publications and press releases"
      - "Academic conference official proceedings"
      - "Government AI policy and research announcements"
    authority_indicators:
      - "Direct from AI companies (OpenAI, Anthropic, Google DeepMind)"
      - "Peer-reviewed research institutions"
      - "Official conference proceedings (NeurIPS, ICML, ICLR)"
    update_patterns:
      expected_frequency: "daily"
      peak_activity_times: ["09:00-12:00 PST", "14:00-17:00 EST"]  # Company announcement windows
      seasonal_patterns: "Increased activity during conference seasons (Dec, Jun, Sep)"
    sources:
      - url: "https://openai.com/blog"
        type: "company_blog"
        authority_score: 1.0
        monitoring_method: "RSS + Fetch"
      - url: "https://anthropic.com/news"
        type: "company_blog" 
        authority_score: 1.0
        monitoring_method: "RSS + Fetch"
      - url: "https://deepmind.google/discover/blog/"
        type: "company_blog"
        authority_score: 1.0
        monitoring_method: "Fetch"
      - url: "https://ai.googleblog.com/"
        type: "company_blog"
        authority_score: 0.95
        monitoring_method: "RSS + Fetch"
      - url: "https://arxiv.org/list/cs.AI/recent"
        type: "research_papers"
        authority_score: 0.95
        monitoring_method: "RSS + Custom Parser"

  tier_2_community:
    description: "AI expert creators, specialized media, research communities"
    discovery_patterns:
      - "AI researcher YouTube channels and blogs"
      - "Specialized AI/ML news and analysis sites"
      - "Expert newsletters and substacks"
      - "Research group blogs and updates"
    authority_indicators:
      - "Recognized AI researchers and practitioners"
      - "High-quality technical content and analysis"
      - "Consistent track record of accurate reporting"
    update_patterns:
      expected_frequency: "daily"
      peak_activity_times: ["08:00-10:00", "15:00-18:00"]
      content_types: ["analysis", "tutorials", "research_summaries", "interviews"]
    sources:
      - url: "https://www.youtube.com/c/YannicKilcher"
        type: "expert_youtube"
        authority_score: 0.9
        monitoring_method: "YouTube MCP"
      - url: "https://huggingface.co/blog"
        type: "platform_blog"
        authority_score: 0.85
        monitoring_method: "RSS + Fetch"
      - url: "https://venturebeat.com/ai/"
        type: "tech_journalism"
        authority_score: 0.8
        monitoring_method: "RSS + Fetch"
      - url: "https://thegradient.pub/"
        type: "research_publication"
        authority_score: 0.85
        monitoring_method: "RSS + Fetch"

  tier_3_aggregators:
    description: "AI/ML discussions, community forums, social media"
    discovery_patterns:
      - "Reddit AI/ML communities"
      - "AI Twitter/X discussions and lists"
      - "HackerNews AI-related discussions"
      - "LinkedIn AI professional groups"
    authority_indicators:
      - "Active communities with quality discussions"
      - "High engagement and thoughtful analysis"
      - "Moderated spaces with expertise validation"
    update_patterns:
      expected_frequency: "hourly"
      peak_activity_times: ["12:00-14:00", "20:00-22:00"]  # Lunch and evening discussion times
      engagement_metrics: ["upvotes", "quality_comments", "expert_participation"]
    sources:
      - url: "https://reddit.com/r/MachineLearning"
        type: "community_forum"
        authority_score: 0.75
        monitoring_method: "Reddit API + Playwright"
      - url: "https://reddit.com/r/artificial"
        type: "community_forum"
        authority_score: 0.7
        monitoring_method: "Reddit API + Playwright"
      - url: "https://news.ycombinator.com"
        type: "tech_aggregator"
        authority_score: 0.8
        monitoring_method: "RSS + Custom Filter"
        filter_keywords: ["AI", "machine learning", "neural", "LLM"]

# Content Analysis and Quality Configuration
content_analysis:
  relevance_scoring:
    keyword_weights:
      primary_keywords: 1.0
      secondary_keywords: 0.7
      topic_context: 0.5
    content_type_weights:
      research_papers: 1.0
      official_announcements: 0.95
      expert_analysis: 0.9
      news_articles: 0.8
      tutorial_content: 0.7
      social_discussions: 0.6

  significance_indicators:
    high_significance:
      - "New model releases (GPT, Claude, Gemini updates)"
      - "Breakthrough research publications"
      - "Major AI company announcements"
      - "Regulatory developments affecting AI"
      - "Safety and alignment breakthroughs"
      - "AGI milestone claims or achievements"
    medium_significance:
      - "Open source model releases"
      - "Conference presentation announcements"
      - "Funding announcements for AI companies"
      - "Industry adoption case studies"
      - "Technical tool and framework releases"
    low_significance:
      - "General AI discussion and speculation"
      - "Minor tool updates"
      - "Repetitive news coverage"
      - "AI art and entertainment applications"

  quality_thresholds:
    minimum_relevance_score: 0.7    # Higher threshold for AI due to hype
    minimum_authority_score: 0.6    # Require good source credibility
    minimum_significance_score: 0.5  # Focus on meaningful developments
    
# MCP Server Configuration for AI/ML Sources
mcp_server_mapping:
  fetch_server:
    use_cases: ["Company blogs", "Research institution sites", "News articles"]
    rate_limits: "1 request per second per domain"
    error_handling: "3 retries with exponential backoff"
    
  github_server:
    use_cases: ["AI framework development", "Model releases", "Research code"]
    repositories: 
      - "openai/openai-python"
      - "anthropics/anthropic-sdk-python"
      - "huggingface/transformers"
      - "google-research/google-research"
      - "microsoft/DeepSpeed"
    monitoring_scope: ["releases", "issues", "discussions"]
    
  youtube_server:
    use_cases: ["Expert analysis", "Conference talks", "Technical tutorials"]
    channels:
      - "UCbfYPyITQ-7l4upoX8nvctg"  # Two Minute Papers
      - "UCWN3xxRkmTPmbKwht9FuE5A"  # Siraj Raval
      - "UCbRTQphi1HNL8bCKYOtOnSQ"  # Yannic Kilcher
    content_types: ["uploads", "live_streams", "premieres"]
    
  playwright_server:
    use_cases: ["Dynamic research sites", "Conference proceedings", "Social media"]
    target_sites:
      - "neurips.cc"  # Dynamic conference content
      - "twitter.com" # AI Twitter discussions
      - "linkedin.com/feed" # Professional AI discussions

# AI Agent Specialization Configuration  
agent_specialization:
  content_specialists:
    technical_analyst:
      focus: "Technical accuracy, model architectures, implementation details"
      expertise_areas: ["neural_networks", "training_techniques", "optimization", "architectures"]
      validation_criteria: ["mathematical_accuracy", "implementation_feasibility", "technical_depth"]
      
    research_analyst:
      focus: "Research paper analysis, academic developments, methodology"
      expertise_areas: ["research_methodology", "experimental_design", "peer_review", "citations"]
      validation_criteria: ["research_quality", "novelty", "reproducibility", "impact"]
      
    industry_analyst:
      focus: "Business applications, market trends, company developments"
      expertise_areas: ["ai_adoption", "business_models", "competitive_landscape", "market_impact"]
      validation_criteria: ["business_relevance", "market_significance", "adoption_potential"]
      
    safety_analyst:
      focus: "AI safety, alignment, ethics, risk assessment"
      expertise_areas: ["ai_safety", "alignment_research", "risk_assessment", "ethics"]
      validation_criteria: ["safety_implications", "ethical_considerations", "risk_factors"]

# Cross-Topic Integration Configuration
cross_topic_integration:
  relationship_types:
    - type: "competitive"
      targets: ["openai", "claude", "google-ai"]
      description: "Companies and models competing in AI space"
    - type: "complementary"  
      targets: ["computer-vision", "nlp", "robotics"]
      description: "AI subfields that enhance each other"
    - type: "dependent"
      targets: ["semiconductors", "cloud-computing", "datasets"]
      description: "Technologies AI development depends on"
    - type: "influential"
      targets: ["crypto", "biotech", "autonomous-vehicles", "finance"]
      description: "Industries being transformed by AI"
      
  shared_sources:
    identification_patterns:
      - "Tech news sites covering multiple technology topics"
      - "General technology journalists and publications"
      - "Venture capital and funding news covering multiple sectors"
    resource_optimization: true
    
  trigger_conditions:
    cross_topic_alerts:
      - "AI breakthroughs affecting cryptocurrency (AI trading, blockchain optimization)"
      - "AI developments in biotech (drug discovery, protein folding)"
      - "Regulatory changes affecting multiple technology sectors"
    
    resource_reallocation:
      - "Major AI conference periods (NeurIPS, ICML, ICLR)"
      - "AI company quarterly earnings and announcements"
      - "AI safety incidents requiring immediate monitoring"

# Performance and Monitoring Configuration
performance_monitoring:
  success_metrics:
    coverage_percentage: 95      # Capture 95% of significant AI news within 1 hour
    relevance_accuracy: 90       # 90% of captured content should be AI-relevant
    false_positive_rate: 15      # Allow slightly higher due to AI hype and broad coverage
    response_time: 600           # 10 minutes for critical AI developments
    
  monitoring_intervals:
    real_time_sources: 300       # 5 minutes for OpenAI, Anthropic, major announcements
    high_priority_sources: 900   # 15 minutes for research papers, expert analysis
    medium_priority_sources: 1800 # 30 minutes for industry news
    low_priority_sources: 3600   # 1 hour for community discussions
    
  resource_allocation:
    max_concurrent_agents: 15    # Higher allocation due to high activity
    processing_priority: "high"  # Top priority for resource allocation
    storage_retention: 730       # 2 years retention for AI developments

# File Organization Configuration
file_organization:
  base_path: "knowledge-vault/topics/ai-ml/"
  structure:
    config: "config/"
    news: "news/"
    research: "research/"
    companies: "companies/"
    models: "models/"
    analysis: "analysis/"
    relationships: "relationships/"
    
  naming_conventions:
    daily_files: "YYYY-MM-DD-{tier}-ai-news.md"
    weekly_files: "YYYY-WW-ai-weekly-digest.md"
    research_files: "YYYY-MM-DD-{venue}-research.md"
    company_files: "YYYY-MM-DD-{company}-updates.md"