#!/bin/bash

echo "🔍 Validating AI Knowledge Base..."

# Check directory structure
echo "Checking directory structure..."
required_dirs=(
    ".claude/commands"
    ".claude/prompts/meta-prompts"
    ".claude/prompts/document-templates/tier1"
    ".claude/prompts/document-templates/tier2"
    ".claude/prompts/document-templates/tier3"
    ".claude/prompts/document-templates/tier4"
    ".claude/tests"
    "ai/context"
    "ai/knowledge/strategic"
    "ai/knowledge/product/prd"
    "ai/knowledge/product/epics"
    "ai/knowledge/product/user-stories"
    "ai/knowledge/product/acceptance-criteria"
    "ai/knowledge/product/release-notes"
    "ai/knowledge/user-experience/research/user-interviews"
    "ai/knowledge/user-experience/research/usability-testing"
    "ai/knowledge/user-experience/research/empathy-maps"
    "ai/knowledge/user-experience/design"
    "ai/knowledge/user-experience/journey-maps"
    "ai/knowledge/technical/api"
    "ai/knowledge/technical/database/schemas"
    "ai/knowledge/technical/architecture/c4-diagrams"
    "ai/knowledge/technical/security"
    "ai/knowledge/business-analysis"
    "ai/knowledge/quality-assurance/test-plans"
    "ai/knowledge/quality-assurance/test-cases"
    "ai/knowledge/quality-assurance/uat-plans"
    "ai/knowledge/compliance/security-docs"
    "ai/features/_template/requirements"
    "ai/features/_template/design"
    "ai/features/_template/technical"
    "ai/features/_template/tests"
    "ai/features/_template/analytics"
    "ai/features/_template/meta"
    "ai/agents/tier-specialists"
    "ai/agents/feature-specialists"
    "ai/agents/orchestrator"
)

for dir in "${required_dirs[@]}"; do
    if [ -d "$dir" ]; then
        echo "✅ $dir exists"
    else
        echo "❌ $dir missing"
    fi
done

# Check required files
echo -e "\nChecking configuration files..."
required_files=(
    ".claude/settings.json"
    ".claude/tests/document-structure-tests.yaml"
    ".claude/tests/dependency-validation-tests.yaml"
    ".claude/tests/ai-context-tests.yaml"
    ".claude/commands/analyse-dependencies.md"
    ".claude/commands/create-document.md"
    ".claude/commands/create-feature.md"
    ".claude/commands/generate-tier-documents.md"
    ".claude/commands/gh-issue.md"
    ".claude/commands/orchestrate-agents.md"
    ".claude/commands/validate-knowledge-base.md"
    "ai/context/dependencies.yaml"
    "ai/context/document-registry.yaml"
    "ai/context/feature-registry.yaml"
    "ai/context/tier-configuration.yaml"
    "ai/features/_template/feature-spec.md"
    "ai/features/_template/README.md"
    "ai/features/_template/design/ui-mockups.md"
    "ai/features/_template/meta/ai-instructions.md"
    "ai/features/_template/requirements/acceptance-criteria.md"
    "ai/features/_template/requirements/user-stories.md"
    "ai/features/_template/technical/api-contracts.md"
    "ai/features/_template/technical/data-models.md"
    "ai/features/_template/tests/test-strategy.md"
    "ai/features/user-authentication/feature-spec.md"
    "ai/prompts/1_discover_tools.md"
    "ai/prompts/2_extract_features.md"
    "ai/prompts/3_map_features_to_framework.md"
    "ai/prompts/document-templates/tier1/api-documentation.md"
    "ai/prompts/document-templates/tier1/database-schemas.md"
    "ai/prompts/document-templates/tier2/prd.md"
    "ai/prompts/document-templates/tier3/user-stories.md"
    "ai/prompts/document-templates/tier4/user-personas.md"
    "ai/prompts/meta-prompts/dependency-analyzer.md"
    "ai/prompts/meta-prompts/document-generator.md"
    "ai/prompts/meta-prompts/feature-orchestrator.md"
    "ai/prompts/meta-prompts/quality-validator.md"
    "ai/prompts/meta-prompts/tier-orchestrator.md"
    "ai/prompts/meta/adaptive_chain_of_thought.md"
    "ai/prompts/meta/complex_research.md"
    "ai/prompts/meta/domain_adaptive.md"
    "ai/prompts/meta/domain_specific_research.md"
    "ai/prompts/meta/iterative_research_refinement.md"
    "ai/prompts/meta/modular_task_decomposition.md"
    "ai/prompts/meta/multi_perspective_approach.md"
    "ai/prompts/meta/primary_research.md"
    "ai/prompts/meta/step_by_step_research.md"
    "ai/prompts/meta/textgrad_iterative.md"
    "ai/prompts/meta/universal_research.md"
    "ai/scratchpads/.gitkeep"
    "ai/tests/ai-context-tests.yaml"
    "ai/tests/dependency-validation-tests.yaml"
    "ai/tests/document-structure-tests.yaml"
)

for file in "${required_files[@]}"; do
    if [ -f "$file" ]; then
        echo "✅ $file exists"
    else
        echo "❌ $file missing"
    fi
done

echo -e "\n✨ Validation complete!"