# Technology Tracking Schema
# Knowledge Vault Integration - AI Knowledge Lifecycle Orchestrator
# Tracks technology versions, release cycles, and change patterns

database_info:
  name: "Technology Tracking"
  type: "specialized_tracking"
  description: "Comprehensive technology version and change pattern tracking"
  version: "1.0.0"
  created: "2025-01-24"
  integration_purpose: "Support AI Knowledge Lifecycle Orchestrator technology monitoring"

properties:
  # Core Identification
  id:
    type: "uuid"
    required: true
    description: "Unique identifier for the technology entry"
    format: "uuid_v4"
    
  technology_name:
    type: "title"
    required: true
    description: "Canonical name of the technology (e.g., React, PostgreSQL, Docker)"
    max_length: 100
    
  # Technology Classification
  category:
    type: "select"
    required: true
    description: "Primary technology category"
    options:
      - value: "frontend_framework"
        name: "Frontend Framework"
        color: "purple"
      - value: "backend_framework"
        name: "Backend Framework"
        color: "blue"
      - value: "database"
        name: "Database"
        color: "green"
      - value: "ci_cd"
        name: "CI/CD"
        color: "orange"
      - value: "cloud_platform"
        name: "Cloud Platform"
        color: "gray"
      - value: "dev_tool"
        name: "Development Tool"
        color: "yellow"
      - value: "ai_ml"
        name: "AI/ML"
        color: "red"
      - value: "security"
        name: "Security"
        color: "brown"
      - value: "infrastructure"
        name: "Infrastructure"
        color: "default"
      - value: "other"
        name: "Other"
        color: "pink"
        
  # Version Tracking
  current_version:
    type: "rich_text"
    required: true
    description: "Current version being tracked (semantic versioning when applicable)"
    
  version_pattern:
    type: "select"
    required: true
    description: "Version numbering pattern used by technology"
    options:
      - value: "semantic"
        name: "Semantic (x.y.z)"
        color: "green"
      - value: "date_based"
        name: "Date-based (YYYY.MM)"
        color: "blue"
      - value: "release_name"
        name: "Release Names"
        color: "purple"
      - value: "build_number"
        name: "Build Numbers"
        color: "orange"
      - value: "other"
        name: "Other Pattern"
        color: "gray"
        
  # Release Cycle Information
  release_frequency:
    type: "select"
    required: false
    description: "Typical release cycle frequency"
    options:
      - value: "weekly"
        name: "Weekly"
        color: "red"
      - value: "monthly"
        name: "Monthly"
        color: "orange"
      - value: "quarterly"
        name: "Quarterly"
        color: "yellow"
      - value: "biannual"
        name: "Bi-annual"
        color: "green"
      - value: "annual"
        name: "Annual"
        color: "blue"
      - value: "irregular"
        name: "Irregular"
        color: "gray"
        
  next_major_release:
    type: "date"
    required: false
    description: "Expected date for next major release (if known)"
    
  # Change Pattern Analysis
  change_volatility:
    type: "select"
    required: false
    description: "Frequency and impact of changes"
    options:
      - value: "high"
        name: "High Volatility"
        color: "red"
      - value: "moderate"
        name: "Moderate Volatility"
        color: "yellow"
      - value: "low"
        name: "Low Volatility"
        color: "green"
      - value: "stable"
        name: "Very Stable"
        color: "blue"
        
  breaking_changes_frequency:
    type: "select"
    required: false
    description: "How often breaking changes occur"
    options:
      - value: "frequent"
        name: "Frequent (>3/year)"
        color: "red"
      - value: "occasional"
        name: "Occasional (1-3/year)"
        color: "yellow"
      - value: "rare"
        name: "Rare (<1/year)"
        color: "green"
      - value: "never"
        name: "Never"
        color: "blue"
        
  # Monitoring Configuration
  monitoring_priority:
    type: "select"
    required: true
    description: "Priority level for monitoring this technology"
    options:
      - value: "critical"
        name: "Critical"
        color: "red"
      - value: "high"
        name: "High"
        color: "orange"
      - value: "medium"
        name: "Medium"
        color: "yellow"
      - value: "low"
        name: "Low"
        color: "blue"
      - value: "archived"
        name: "Archived"
        color: "gray"
        
  monitoring_sources:
    type: "multi_select"
    required: false
    description: "Official sources for monitoring updates"
    options:
      - value: "github_releases"
        name: "GitHub Releases"
        color: "blue"
      - value: "npm_registry"
        name: "NPM Registry"
        color: "red"
      - value: "official_blog"
        name: "Official Blog"
        color: "green"
      - value: "changelog"
        name: "Changelog"
        color: "purple"
      - value: "rss_feed"
        name: "RSS Feed"
        color: "orange"
      - value: "twitter"
        name: "Twitter/X"
        color: "blue"
      - value: "mailing_list"
        name: "Mailing List"
        color: "gray"
      - value: "other"
        name: "Other"
        color: "pink"
        
  official_urls:
    type: "rich_text"
    required: false
    description: "Official URLs for monitoring (JSON array format)"
    
  # Impact Assessment
  ecosystem_impact:
    type: "select"
    required: false
    description: "Impact level on broader technology ecosystem"
    options:
      - value: "foundational"
        name: "Foundational"
        color: "red"
      - value: "influential"
        name: "Influential"
        color: "orange"
      - value: "moderate"
        name: "Moderate"
        color: "yellow"
      - value: "niche"
        name: "Niche"
        color: "blue"
        
  dependency_criticality:
    type: "select"
    required: false
    description: "Criticality for AI instruction dependencies"
    options:
      - value: "essential"
        name: "Essential"
        color: "red"
      - value: "important"
        name: "Important"
        color: "orange"
      - value: "useful"
        name: "Useful"
        color: "yellow"
      - value: "optional"
        name: "Optional"
        color: "blue"
        
  # Historical Data
  first_tracked:
    type: "created_time"
    required: true
    description: "When tracking for this technology began"
    
  last_updated:
    type: "last_edited_time"
    required: true
    description: "When technology information was last updated"
    
  last_version_change:
    type: "date"
    required: false
    description: "Date of most recent version change"
    
  # Metadata and Context
  description:
    type: "rich_text"
    required: false
    description: "Technology description and context"
    
  vendor_organization:
    type: "rich_text"
    required: false
    description: "Organization or vendor maintaining the technology"
    
  license_type:
    type: "select"
    required: false
    description: "License type"
    options:
      - value: "open_source"
        name: "Open Source"
        color: "green"
      - value: "commercial"
        name: "Commercial"
        color: "blue"
      - value: "dual_license"
        name: "Dual License"
        color: "purple"
      - value: "proprietary"
        name: "Proprietary"
        color: "red"
      - value: "unknown"
        name: "Unknown"
        color: "gray"
        
  # Relationships
  dependency_mappings:
    type: "relation"
    required: false
    description: "Related dependency mapping entries"
    related_database: "dependency_mapping"
    dual_property: "technology_tracking_relations"
    
  change_events:
    type: "relation"
    required: false
    description: "Related change events"
    related_database: "change_events"
    dual_property: "technology_tracking_relations"
    
  knowledge_vault_relations:
    type: "relation"
    required: false
    description: "Related knowledge vault items"
    related_database: "knowledge_vault"
    dual_property: "technology_tracking_relations"

# Database Configuration
configuration:
  # Technology-specific configuration
  technology_focus: true
  versioning_support: true
  change_tracking: true
  
  # Validation Rules
  validation:
    required_fields: ["id", "technology_name", "category", "current_version", "monitoring_priority"]
    unique_fields: ["id", "technology_name"]
    url_validation: true
    version_format_validation: true
    
  # File Organization
  file_structure:
    base_path: "knowledge-vault/databases/technology_tracking/"
    item_path: "items/"
    relation_path: "relations/"
    schema_path: "technology_tracking_schema.yaml"
    
  # Integration Settings
  orchestrator_integration:
    enabled: true
    change_detection_integration: true
    dependency_registry_sync: true
    auto_update_capability: true
    
# Index Configuration
indexes:
  - fields: ["technology_name", "category"]
    description: "Technology lookup and categorization"
  - fields: ["monitoring_priority", "change_volatility"]
    description: "Monitoring prioritization"
  - fields: ["last_version_change"]
    description: "Recent changes tracking"
  - fields: ["dependency_criticality"]
    description: "Dependency impact analysis"
    
# Views Configuration
views:
  critical_monitoring:
    name: "Critical Monitoring"
    filter:
      monitoring_priority: ["critical", "high"]
    sort:
      - field: "last_version_change"
        direction: "descending"
        
  high_volatility:
    name: "High Volatility"
    filter:
      change_volatility: ["high", "moderate"]
    sort:
      - field: "monitoring_priority"
        direction: "descending"
        
  recent_changes:
    name: "Recent Changes"
    sort:
      - field: "last_version_change"
        direction: "descending"
    limit: 25
    
  by_category:
    name: "By Category"
    group_by: "category"
    sort:
      - field: "monitoring_priority"
        direction: "descending"

# Integration Points
integration_points:
  change_detection_system:
    data_flow: "bidirectional"
    update_frequency: "real_time"
    conflict_resolution: "change_detection_authoritative"
    
  dependency_registry:
    data_flow: "bidirectional"
    sync_fields: ["technology_name", "current_version", "dependency_criticality"]
    consistency_requirements: "eventual_consistency"
    
  knowledge_vault:
    relationship_type: "hub_integration"
    cross_references: true
    shared_tagging: true